image: Visual Studio 2022

environment:
    matrix:
        - PYTHON: Python38
        - PYTHON: Python310

install:
    - C:\%PYTHON%\Scripts\pip install -e .
    - C:\%PYTHON%\Scripts\pip install -r dev_requirements.txt

build: off

test_script:
    - C:\%PYTHON%\Scripts\pytest test\
